fix invisible dummies
NuclearPowered/Reactor pull request #21
Opened 2021-04-04 16:40 UTC by Galster-dev

`PlayerControl#ClientInitialize` checks for `Data.IsIncomplete` before making player visible back so we have to set all the stuff (hat, skin, pet etc)
Also added TranslationController because why not

2021-04-04 19:21 UTC, js6pak requested changes

2021-04-04 19:21 UTC, js6pak commented on Reactor.Debugger/DebuggerPlugin.cs
> +                        playerControl.isDummy = true;
isn't this set by the prefab?

2021-04-04 19:21 UTC, js6pak commented on Reactor.Debugger/DebuggerPlugin.cs
> +                        playerControl.SetHat(0, playerControl.Data.ColorId);
maybe make all of these "random" for more testness? (just do `i % HatManager.Instance.Hats.Length` etc)

2021-04-04 19:55 UTC, Galster-dev commented on Reactor.Debugger/DebuggerPlugin.cs
> +                        playerControl.isDummy = true;
didn't look into it, but i don't think so because `TutorialManager#RunTutorial` is the only place where it's being assigned (as i remember)

2021-04-04 19:55 UTC, Galster-dev commented on Reactor.Debugger/DebuggerPlugin.cs
> +                        playerControl.SetHat(0, playerControl.Data.ColorId);
in-built dummies will not have hats etc but why not

2021-04-04 19:59 UTC, js6pak commented on Reactor.Debugger/DebuggerPlugin.cs
> +                        playerControl.isDummy = true;
since like it was added after this feature was added, fine then

2021-04-04 20:51 UTC, Sanae6 commented on Reactor.Debugger/DebuggerPlugin.cs
> +                        playerControl.isDummy = true;
it's set by the prefab, don't set it yourself

2021-04-13 19:27 UTC, js6pak approved these changes

2021-04-13 19:36 UTC, merged