Add localization API
NuclearPowered/Reactor pull request #64
Opened 2022-10-07 09:06 UTC by AlexejheroYTB

2022-10-11 14:57 UTC, AlexejheroYTB commented
This pull request is ready to be merged. @js6pak

Let me know if you have any other changes that you want me to make

2022-10-13 15:39 UTC, js6pak requested changes

2022-10-13 15:39 UTC, js6pak commented on Reactor/Localization/Providers/HardCodedLocalizationProvider.cs
> +        return true;
```suggestion
        return Strings.TryGetValue(stringName, out result);
```

2022-10-13 15:39 UTC, js6pak commented on Reactor/Localization/Providers/HardCodedLocalizationProvider.cs
> +    internal static readonly Dictionary<StringNames, string> Strings = new();
```suggestion
    private static readonly Dictionary<StringNames, string> _strings = new();
```

2022-10-13 15:39 UTC, js6pak commented on Reactor.Example/ExamplePlugin.cs
> +                    }
This can be moved out of the `AmongUsClient.Instance && PlayerControl.LocalPlayer` if check

2022-10-13 15:39 UTC, js6pak commented on Reactor/Localization/LocalizationManager.cs
> +        stringName = StringNames.ExitButton;
Why `ExitButton`? Wouldn't `NoTranslation` or `null` be better?

2022-10-13 15:49 UTC, AlexejheroYTB commented on Reactor/Localization/LocalizationManager.cs
> +        stringName = StringNames.ExitButton;
It doesnt matter what you set it to because the prefix returns false and the base-game method is called.

However, this mimics base-game behaviour where a missing system type or task type will return exit button. because it is `(StringNames) 0`.

2022-10-13 15:53 UTC, js6pak commented on Reactor/Localization/LocalizationManager.cs
> +        stringName = StringNames.ExitButton;
That probably means the base game is using `default` so we should aswell.

2022-10-23 13:26 UTC, js6pak approved these changes

2022-10-23 13:36 UTC, merged